import service1 from "../images/service1.png"
import service2 from "../images/service2.png"
import service3 from "../images/service3.png"
import service4 from "../images/service4.png"
import service5 from "../images/service5.png"
import service6 from "../images/service6.png"
import service7 from "../images/service7.png"
import service8 from "../images/service8.png"
import service9 from "../images/service9.png"
import service10 from "../images/service10.png"

export default
 [
      {image : service1 , title:"Web Design & Development", content:"Web Design + Development:- Our Web designers are creative professionals with a strong understanding of client needs and business objectives. They are skilled in graphic design, HTML, CSS, and JavaScript, and use their knowledge to create visually appealing and user-friendly websites that meet the specific needs of our clients. Our designers are dedicated to providing exceptional customer service, staying current with the latest web technologies, and delivering projects on time. With their talent, expertise, and commitment, they help our clients achieve their online goals and drive success through their websites."},
      {image : service2 , title:"App Design & Development", content:"Android App Development:- Our App Developers are skilled professionals with a passion for creating innovative and functional mobile applications. They possess extensive knowledge of programming languages and software development methodologies, and use this expertise to bring our clients ideas to life. Our developers are experienced and understand our clients needs and translate them into high-quality, user-friendly apps that meet their specific requirements. They are experts in creating apps that are optimized for performance, stability, and security, and are committed to delivering projects on time. With their talent and dedication, they help clients achieve their business goals and succeed in the mobile app market."},
      {image : service3 , title:"Graphic Design", content:"Graphics Designer:- Our Graphic Designers are creative professionals with a passion for visual communication. They possess a strong understanding of design principles, typography, and color theory, and use these skills to create visually appealing designs that meet the specific needs of our clients. They are experienced in a range of design software, including Adobe Creative Suite, and are able to translate ideas into high-quality graphics that effectively communicate our client's message. With their talent, expertise, and commitment to quality, they help clients achieve their marketing and branding objectives and make a lasting impression through their designs."},
      {image : service4 , title:"Vfx & Motion Design", content:"Visual Effects/Motion Designer:- Our VFX artists are skilled professionals with a passion for visual effects and storytelling. They use their expertise in animation, compositing, and video production to bring our clients ideas to life through engaging and realistic visual effects. They possess a strong understanding of VFX software and techniques, including industry-standard tools like Adobe After Effects and Nuke, and use this knowledge to create high-quality effects that meet the specific needs of our clients. These artists are experienced and understand our clients goals and translate them into compelling visuals that effectively communicate their message."},
      {image : service5 , title:"Discord Services", content:"Smart Contract Development & Whitepaper:-Our Smart Contract Developers are skilled professionals with a passion for blockchain technology and its applications. They possess extensive knowledge of smart contract programming languages such as Solidity, and use this expertise to create secure, reliable, and automated decentralized applications for our clients. They are experienced and understand our clients needs and translate them into functional smart contracts that meet their specific requirements. With their talent, expertise, and commitment, they help our clients harness the power of blockchain technology to automate processes, improve security, and drive innovation in their business."},
      {image : service6 , title:"Smart Contract & Whitepaper", content:"Discord Services :- Discord Server Creation , Discord Moderators , Discord Collaborations "},
      {image : service7 , title:"Nft Artists", content:"Our NFT artists are creative professionals with a passion for digital art and blockchain technology. Our NFT Artists use their skills in digital art and graphic design to create unique and visually appealing 2d & 3d NFTs for our clients, whether for personal projects or for commercial purposes. With their talent, expertise, and commitment, they help clients harness the power of NFTs to monetize their art creatively and reach new audiences."},
      {image : service8 , title:"Build ur Own Staking Platform", content:"Build your own NFT Staking Platform:- Our NFT Staking Platform Developers are skilled professionals with a passion for blockchain technology and NFTs. They possess extensive knowledge of smart contract programming languages, staking protocols, and the latest developments in the NFT space. They use their expertise to create secure, reliable, and automated NFT staking solutions for our clients, helping them maximize returns on their NFT investments. These developers are experienced and understand our clients goals and translate them into functional and optimized staking solutions that meet their specific requirements."},
      {image : service9 , title:"Create ur Own Crypto", content:"Launch Your Own Crypto Token:- Our Cryptocurrency Developers are skilled professionals with a passion for blockchain technology and digital currencies. They possess extensive knowledge of cryptocurrency protocols and the latest developments in the crypto space, and use their expertise to create secure, reliable, and scalable solutions for our clients. Our developers are experienced and understand our clients needs and translate them into functional and optimized cryptocurrency solutions, such as wallets, exchanges, and payment systems. With their talent, expertise, and commitment, they help clients harness the power of blockchain technology and digital currencies to drive growth and achieve their goals in the crypto space."},
      {image : service10 , title:"Launch ur Own Merchandise", content:"We can design, manufacture and deliver the best quality merchandise (including Shirts, caps, bagpacks, hoodies etc.) into whole over the world."}
    ]
